optimized distance check
qbcore-framework/qb-apartments pull request #45
Opened 2022-01-01 06:27 UTC by yamieboi

**_**Noticed QB-apartments running high so took a look and found an issue with the distance check and fixed that and had  to lower the thread sleep from 10000 to 5000, from 0.4-5 to 0.0 while not close to a apartment TESTED***_*

First, make sure you've read and are following the contribution guidelines and style guide and your code reflect that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- yes
- Does your code fit the style guidelines? [yes]
- yes
- Does your PR fit the contribution guidelines? [yes]
- yes

2022-01-01 06:49 UTC, ARSSANTO requested changes
LocalPlayer.state.isLoggedIn  use like this rather then LocalPlayer.state['isLoggedIn']

2022-01-02 15:18 UTC, yamieboi commented
> LocalPlayer.state.isLoggedIn use like this rather then LocalPlayer.state['isLoggedIn']

Alright done may this get approved now hehe

2022-01-02 15:19 UTC, ARSSANTO approved these changes

2022-01-15 02:25 UTC, FjamZoo commented
This one is good to merge

2022-01-16 06:06 UTC, merged