Update for qb-target
qbcore-framework/qb-apartments pull request #60
Opened 2022-03-04 01:04 UTC by deandum

To enable `qb-target` for apartments, change `Apartments.UseTarget` to `true` in `config.lua`.

2022-03-04 03:26 UTC, iktray approved these changes

2022-03-06 18:51 UTC, BerkieBb commented
It's not good to register target exports in a loop

2022-03-07 14:04 UTC, deandum commented
> It's not good to register target exports in a loop

There is a `created` field on each zone created so that it is only initiated once. The loop is used to update the targets if the player moves to a new apartment, but the zones are created just once.

2022-03-07 17:06 UTC, BerkieBb commented
I see

2022-03-07 17:06 UTC, BerkieBb approved these changes

2022-03-10 21:11 UTC, DannysRP commented
Not sure if this is a issue with apartments or target but I've heard from others that the target option does not show up at the exit if you are still using the gabz default apartment.

2022-03-11 16:39 UTC, deandum commented
> Not sure if this is a issue with apartments or target but I've heard from others that the target option does not show up at the exit if you are still using the gabz default apartment.

qb-target is not just a plug-and-play mechanic. The PZ has to be on top of an entity to work well, otherwise, there is nothing to target (that's how raycasting works in this game). With that being said, I don't know what `gabz default apartment` is, but you might just need to update the coords and the offset in the config file to match with your needs.

2022-03-11 16:42 UTC, DannysRP commented
This was an issue other people have stated in support within the QBCore discord. Gabz pink cage apartment used the be the default apartment on all QBCore builds until it got updated a while back to the new starting apartment. Some people still use the old apartment and were having said issue I was speaking of

2022-03-13 07:30 UTC, DannysRP commented
Small issue. When you leave your apartment after creating a new character the apartment says "Move Here" instead of "Enter Apartment". Only way to fix is either leave and join back or restart qb-apartments. Only noticed this with target config

2022-03-15 00:39 UTC, deandum commented
> Small issue. When you leave your apartment after creating a new character the apartment says "Move Here" instead of "Enter Apartment". Only way to fix is either leave and join back or restart qb-apartments. Only noticed this with target config

Isn't it random which apartment is assigned to you? It is possible that this can happen, but I don't think it is necessarily an issue.

2022-03-15 00:52 UTC, DannysRP commented
No you choose an apartment upon your time entering the server. Then when you leave and try to enter it says "Move Here" instead of "Enter Apartment"

2022-03-15 01:12 UTC, deandum commented
> No you choose an apartment upon your time entering the server. Then when you leave and try to enter it says "Move Here" instead of "Enter Apartment"

Ok... try again

2022-03-15 01:25 UTC, DannysRP commented
When I get a chance I'll check it out and let you know if I see any other issues

2022-03-15 08:41 UTC, BerkieBb approved these changes

2022-03-17 21:21 UTC, ItsANoBrainer requested changes
LGTM after these requested changes. Tested both target and menu of everything.

2022-03-17 23:30 UTC, deandum commented on client/main.lua
> +    exports['qb-menu']:showHeader(headerMenu)
Thanks! Copy paste 🤦‍♂️

2022-03-17 23:31 UTC, deandum commented on client/main.lua
> +    exports['qb-menu']:showHeader(headerMenu)
Copy paste 🤦‍♂️

2022-03-18 00:13 UTC, Muri22 approved these changes

2022-03-18 16:02 UTC, ItsANoBrainer commented on client/main.lua
>              local vehicleMenu = {
Theres more to change than just this line, the rest of the references below also use vehicleMenu and need to be changed

2022-03-19 19:25 UTC, deandum commented on client/main.lua
>              local vehicleMenu = {
Yeah, I actually updated those, but never pushed the changes until now. It should be good

2022-03-20 04:47 UTC, ItsANoBrainer approved these changes

2022-03-28 01:45 UTC, merged